import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const currentDir = dirname(fileURLToPath(import.meta.url))
const appVue = readFileSync(resolve(currentDir, '../App.vue'), 'utf8')
const hardwareSparkline = readFileSync(resolve(currentDir, '../components/HardwareSparkline.vue'), 'utf8')
const fontAwesomeIcons = readFileSync(resolve(currentDir, '../icons/fontAwesomeIcons.ts'), 'utf8')

function getStyleBlock(source: string, selectorPattern: RegExp) {
  const match = source.match(selectorPattern)
  assert.ok(match?.groups?.body, `missing style block: ${selectorPattern}`)
  return match.groups.body
}

test('hardware status replaces network speed charts', () => {
  assert.match(appVue, /<div\s+class="hardware-labels"\s+aria-label="硬件指标">/)
  assert.match(appVue, /hardware-cpu-icon fa-solid fa-microchip/)
  assert.match(appVue, /hardware-memory-icon fa-solid fa-memory/)
  assert.match(fontAwesomeIcons, /'fa-solid fa-microchip':\s*\{/)
  assert.match(fontAwesomeIcons, /'fa-solid fa-memory':\s*\{/)
  assert.match(appVue, /<span\s+class="hardware-label-box">\s*<span\s+class="hardware-label-text">CPU 使用占比<\/span>\s*<\/span>/)
  assert.match(appVue, /<span\s+class="hardware-label-box">\s*<span\s+class="hardware-label-text">物理内存占比<\/span>\s*<\/span>/)
  assert.match(appVue, /<strong\s+class="hardware-cpu">\{\{\s*hardwareCpuLabel\s*\}\}<\/strong>/)
  assert.match(appVue, /<ATooltip\s+:title="hardwareMemoryTooltip"\s+placement="top">/)
  assert.match(appVue, /<strong\s+class="hardware-memory">\{\{\s*hardwareMemoryLabel\s*\}\}<\/strong>/)
  assert.match(appVue, /hardwareMemoryTooltip/)
  assert.match(appVue, /formatMemoryBytes/)
  assert.match(appVue, /memoryUsedBytes/)
  assert.match(appVue, /getHardwareStatus/)
  assert.match(appVue, /HARDWARE_POLL_INTERVAL_MS\s*=\s*500/)
  assert.match(appVue, /startHardwarePolling\(\)/)
  assert.match(appVue, /stopHardwarePolling\(\)/)
  assert.doesNotMatch(appVue, /speed-icon fa-solid fa-chart-line/)
  assert.doesNotMatch(appVue, /当前速率/)
  assert.doesNotMatch(appVue, /traffic[A-Z]|Traffic|uploadRate|downloadRate|getTaskTraffic/)

  const labelBlock = getStyleBlock(appVue, /\.hardware-labels\s*\{(?<body>[\s\S]*?)\}/)
  const labelRowBlock = getStyleBlock(appVue, /\.hardware-label-row\s*\{(?<body>[\s\S]*?)\}/)
  const labelIconBlock = getStyleBlock(appVue, /\.hardware-label-icon\s*\{(?<body>[\s\S]*?)\}/)
  const labelBoxBlock = getStyleBlock(appVue, /\.hardware-label-box\s*\{(?<body>[\s\S]*?)\}/)
  const labelTextBlock = getStyleBlock(appVue, /\.hardware-label-text\s*\{(?<body>[\s\S]*?)\}/)
  const chartBlock = getStyleBlock(appVue, /\.mini-chart\s*\{(?<body>[\s\S]*?)\}/)
  const cpuBlock = getStyleBlock(appVue, /\.hardware-cpu\s*\{(?<body>[\s\S]*?)\}/)
  const memoryBlock = getStyleBlock(appVue, /\.hardware-memory\s*\{(?<body>[\s\S]*?)\}/)

  assert.match(hardwareSparkline, /import \{ Chart \} from '@antv\/g2'/)
  assert.match(hardwareSparkline, /type:\s*'line'/)
  assert.match(hardwareSparkline, /shape:\s*'smooth'/)
  assert.match(hardwareSparkline, /padding:\s*0/)
  assert.match(hardwareSparkline, /inset:\s*0/)
  assert.match(hardwareSparkline, /CPU_LANE/)
  assert.match(hardwareSparkline, /MEMORY_LANE/)
  assert.match(hardwareSparkline, /displayValue/)
  assert.match(hardwareSparkline, /MIN_VISIBLE_RANGE_PERCENT/)
  assert.match(hardwareSparkline, /resolveAdaptiveDomain/)
  assert.match(hardwareSparkline, /resolveLaneValue\(cpu,\s*CPU_LANE,\s*cpuDomain\)/)
  assert.match(hardwareSparkline, /resolveLaneValue\(memory,\s*MEMORY_LANE,\s*memoryDomain\)/)
  assert.doesNotMatch(hardwareSparkline, /normalizePercent\(percent\)\s*\/\s*100\)\s*\*\s*lane\.amplitude/)
  assert.match(hardwareSparkline, /elapsedSeconds/)
  assert.match(hardwareSparkline, /x:\s*'elapsedSeconds'/)
  assert.match(hardwareSparkline, /y:\s*'displayValue'/)
  assert.doesNotMatch(hardwareSparkline, /x:\s*'index'/)
  assert.match(hardwareSparkline, /domainMax:\s*CHART_HEIGHT/)
  assert.match(hardwareSparkline, /changeData\(/)
  assert.match(hardwareSparkline, /--green/)
  assert.match(hardwareSparkline, /--blue/)
  assert.doesNotMatch(hardwareSparkline, /<svg/)
  assert.match(labelBlock, /grid-template-rows:\s*repeat\(2,\s*1fr\);/)
  assert.match(labelRowBlock, /grid-template-columns:\s*16px\s+88px;/)
  assert.match(labelIconBlock, /color:\s*var\(--blue\);/)
  assert.match(labelBoxBlock, /display:\s*block;/)
  assert.match(labelBoxBlock, /width:\s*88px;/)
  assert.match(labelTextBlock, /display:\s*block;/)
  assert.match(labelTextBlock, /width:\s*100%;/)
  assert.match(labelTextBlock, /color:\s*var\(--ink-muted\);/)
  assert.match(labelTextBlock, /font-weight:\s*400;/)
  assert.match(labelTextBlock, /text-align:\s*justify;/)
  assert.match(labelTextBlock, /text-align-last:\s*justify;/)
  assert.match(labelTextBlock, /text-justify:\s*inter-character;/)
  assert.match(chartBlock, /transform:\s*translateY\(7px\);/)
  assert.doesNotMatch(cpuBlock, /hardware-cpu-icon/)
  assert.doesNotMatch(memoryBlock, /hardware-memory-icon/)
  assert.match(cpuBlock, /color:\s*var\(--green\);/)
  assert.match(memoryBlock, /color:\s*var\(--blue\);/)
})
